myNextApp:
  component: "@sls-next/serverless-component@latest"
  inputs:
    # Lambda configuration
    lambda:
      memory: 1024
      timeout: 30
    # Build configuration
    build:
      env:
        NODE_ENV: production

